### PR TITLE
Theo/index profile changes

### PR DESCRIPTION
**Pull request by Timer00**
On profile form page, username and email are now required
When a user connects their account, they will be redirected to /editprofile or /archive based on their profile status
Changed index to feed on navbar

### CODE REVIEW

**Comment by Timer00** [comment]
[Modify Index + profile](https://trello.com/c/bqgaQrTq/93-modify-index-profile)

**Comment by Timer00** [comment]
[Modify Index + profile](https://trello.com/c/bqgaQrTq/93-modify-index-profile)

**Comment by Timer00** [comment]
[Modify Index + profile](https://trello.com/c/bqgaQrTq/93-modify-index-profile)

**Comment by hmalkawi1** [comment]
Things look good when testing. However, for a new user, when they sign in and are sent to set up a profile page, I'm getting some errors when clicking submit:

Console error

supabseError

These errors refer to superbase returning a 404 and don't allow you to submit and create a new profile. 

The payload for the request seems to only include the username and the Response is an empty array `[]`

**Review by hmalkawi1 — CHANGES_REQUESTED** [review]
Check the previous comment ^

**Comment by Timer00** [comment]
[Change default image from diamond to something else](https://trello.com/c/xAarVBEG/114-change-default-image-from-diamond-to-something-else)

**Review by hmalkawi1 — CHANGES_REQUESTED** [review]
- When I'm in the submission page, looking at a song, if I refresh from there, it will refresh to Home Screen but then after a second send me back to the "Feed" instead of just staying on the submission page. This is not a bug on production right now, so It's something in this PR.
- When I cosign a song (from the feed), it updates on the feed page, but when I go to the submission page its not there and I can submit again on the same diamond that is cosigned by me

**Pull request merged**
